### ISSUE TITLE
SEtools error

### ISSUE THREAD

**Issue by gxp18** [xmikos/setools-android#11]
Has anyone encountered this error before?

```
setools-android/libs/x86_64$ . sesearch                      
__requires__: command not found                                                                           
bash: /usr/local/bin/sesearch: line 4: syntax error near unexpected token `'pkg_resources''               
bash: /usr/local/bin/sesearch: line 4: `__import__('pkg_resources').require('setools==4.0.0a3')'
```

**Comment by pasis** [comment]
Here you execute `sesearch` from `/usr/local/bin/sesearch` where you have installed python-based `setools` version 4. Current repository has nothing common with the python version of `setools`.

If you want to run sesearch on your x86_64 Linux (or other *nix, but not Android), you can't simply run binary after ndk-build. This is because ndk-build links binaries with Android's libraries and they're absent on Linux.

To run `setools-android` on Linux you need to download this repository: https://github.com/pasis/setools-android (or wait until @xmikos merges it to the current repo). Then run:
```
autoreconf -i
./configure
make
```
The above commands build setools-android to run on your host system.

**Comment by xmikos** [comment]
Updates by @pasis are now merged, you can build latest setools-android version 1.3 with autotools on Linux.
